services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret_root
      MYSQL_DATABASE: iot_db
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
  db_gui:
    image: adminer
    container_name: db_gui
    restart: always
    ports:
      - "3307:8080"
    depends_on:
      - db